# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Viafoura' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'LoginRadiusSDK', '~> 5.4.2'
  pod 'Google-Mobile-Ads-SDK'
  pod 'FirebaseAnalytics'
end
