# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Viafoura' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'LoginRadiusSDK', '~> 5.6.2'
  pod 'Google-Mobile-Ads-SDK'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseMessaging'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
