# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform(:ios)

def delete_temp_keychain(name)
  delete_keychain(
   name: name
   ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0)
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

keychain_name = "KEYCHAIN_USER"
keychain_password = "KEYCHAIN_PASSWORD"

platform :ios do

   #### execute by running "fastlane makeAndSendBuild"
   desc "Make the EOS build and send it to TF"
   lane :makeAndSendBuildProd do

	ensure_temp_keychain(keychain_name, keychain_password)
      app_store_connect_api_key(
         key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
         issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
         key_content: ENV["APP_STORE_CONNECT_CONTENT"],
         is_key_content_base64: true,
         duration: 1200,
         in_house: false)

      match(type: "appstore",
         app_identifier: "com.viafoura.sampleapp",
         git_basic_authorization: ENV["MATCH_GIT_REPOSITORY_TOKEN"],
	      readonly: true,
         keychain_name: keychain_name,
         keychain_password: keychain_password)

      # Increment build number
      appStoreBuild = app_store_build_number(live: false, app_identifier: "com.viafoura.sampleapp")
      
      buildNumber = appStoreBuild.to_i + 1
      increment_build_number_in_plist(
	      target: "Viafoura",
	      build_number: buildNumber.to_s)
      
      gym(scheme: "Viafoura",
        export_method: "app-store",
        configuration: "Release",
        workspace: "Viafoura.xcworkspace")

      upload_to_testflight(skip_waiting_for_build_processing: true)
      delete_temp_keychain(keychain_name)
   end

end