name: Run Fastlane Actions

on:
  push:
    branches: [ main, "CI/CD" ]
  pull_request:
        branches: [ "CI/CD" ]
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Fastlane
      run: |
        brew install fastlane

    - name: Push cocoapods version
      run: |
        pod trunk push ViafouraCore.podspec
