name: Run Fastlane Actions

on:
  push:
    branches: [ main, "CI/CD" ]
  pull_request:
        branches: [ "CI/CD" ]
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: Push cocoapods version
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push ViafouraCore.podspec
